### ISSUE TITLE
Pre-trained model 

### ISSUE THREAD

**Issue by chengjunfengmaster** [Spark001/AsymmNet#1]
Do you have a pre-trained model? Could you please post the trained weights?

**Comment by Spark001** [comment]
OK, the weight has been uploaded with the log.

Please refer to the latest commit.

**Comment by chengjunfengmaster** [comment]
Thank you very much, do you have the weight of the recently released pytorch version of the model?

**Comment by Spark001** [comment]
Sorry for no weight in pytorch now.

If urgent, maybe you can transfer the weight from mxnet to onnx, then transfer to pytorch.

mxnet to onnx is easy, and onnx to pytorch could refer to following code:
```
import onnx
from onnx2pytorch import ConvertModel
import argparse
import torch

parser = argparse.ArgumentParser("onnx->pytorch")
parser.add_argument('-w', "--onnxpath", type=str, required=True)
parser.add_argument('-o', "--outpath", type=str, required=True)

def onnx2torch():
    args = parser.parse_args()
    path_to_onnx_model = args.onnxpath
    onnx_model = onnx.load(path_to_onnx_model)
    pytorch_model = ConvertModel(onnx_model)

    torch.save(pytorch_model.state_dict(), args.outpath)

```

**Comment by chengjunfengmaster** [comment]
Thanks for your help. mxnet to onnx need some documents，such as symbol.json.Do you have such documents? 

sym = './symbol.json'
params = './model.params'
input_shape = (1,3,224,224)
onnx_file = './model.onnx'
converted_model_path = onnx_mxnet.export_model(sym, params, [input_shape], np.float32, onnx_file)
